import jsdom from "jsdom"
import { htmlToPdfMake } from "@/libs/html-to-pdfmake"
import { type Content } from "@/libs/pdfmake"

const { JSDOM } = jsdom
const { window } = new JSDOM("")

export const templatePdf = (): Content => {
  const HTML = `
    <html lang="pt-BR">
      <head>
        <meta charset="UTF-8">
        <title>Note API TDD</title>
      </head>
      <style>
        html, body {
          margin: 0;
          padding: 0;
        }
      </style>
      <body style="margin:0;padding:0;">
        <div style="display: flex;flex-direction: column;">
          <h1 style="color: red;">Note API TDD</h1>
          <p style="color: blue;">Example pdf</p>
        
          <table>
            <tr>
              <th>Company</th>
              <th>Headquarters</th>
              <th>Country</th>
            </tr>
            <tr>
              <td>Google</td>
              <td>Mountain View, California</td>
              <td>United States</td>
            </tr>
            <tr>
              <td>Facebook</td>
              <td>Menlo Park, California</td>
              <td>United States</td>
            </tr>
            <tr>
              <td>Bosch</td>
              <td>Gerlingen</td>
              <td>Germany</td>
            </tr>
            <tr>
              <td>Honda</td>
              <td>Minato City, Tokyo</td>
              <td>Japan</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
            <tr>
              <td>Tata</td>
              <td>Mumbai</td>
              <td>India</td>
            </tr>
          </table>
        </div>
      </body>
    </html>
  `

  return htmlToPdfMake(HTML, {
    window
  })
}
