-- CreateTable
CREATE TABLE "USERS" (
    "USER_ID" TEXT NOT NULL PRIMARY KEY,
    "FULL_NAME" TEXT NOT NULL,
    "AGE" INTEGER NOT NULL,
    "USERNAME" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "PROFILE_PICTURE_URL" TEXT NOT NULL
);
